[versions]
springBoot = "3.5.14"
lombok = "1.18.40"
rome = "2.1.0"
springdoc = "2.8.16"
spotless = "8.4.0"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-quartz = { module = "org.springframework.boot:spring-boot-starter-quartz" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
postgresql = { module = "org.postgresql:postgresql" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
rome = { module = "com.rometools:rome", version.ref = "rome" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
springdoc-openapi-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
